name: Run Tests

on:
  pull_request:
    branches: [main] 

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest tests  # Run tests using pytest (adjust command if using a different test runner)
